version: "3.6"
services:
  client:
    container_name: voting-app
    build: ./
    tty: true
    ports:
      - "3001:3000"
    restart: always
    # command: npm run start
    volumes:
      - ./:/usr/src
    working_dir: /usr/src
networks:
  app-network:
    driver: bridge
